#!/usr/bin/env php
<?php declare(strict_types=1);
////////////////////////////////////////////////////////////////////////////////
// __________ __             ________                   __________
// \______   \  |__ ______  /  _____/  ____ _____ ______\______   \ _______  ___
//  |     ___/  |  \\____ \/   \  ____/ __ \\__  \\_  __ \    |  _//  _ \  \/  /
//  |    |   |   Y  \  |_> >    \_\  \  ___/ / __ \|  | \/    |   (  <_> >    <
//  |____|   |___|  /   __/ \______  /\___  >____  /__|  |______  /\____/__/\_ \
//                \/|__|           \/     \/     \/             \/            \/
// -----------------------------------------------------------------------------
//          Designed and Developed by Brad Jones <brad @="bjc.id.au" />
// -----------------------------------------------------------------------------
////////////////////////////////////////////////////////////////////////////////

require_once(__DIR__.'/vendor/autoload.php');

class RoboFile extends \Robo\Tasks
{
    /**
     * Runs unit tests, with code coverage report.
     */
    public function test()
    {
        exit
        (
            $this->taskPHPUnit()
            ->arg('./tests')
            ->option('coverage-clover', './build/logs/clover.xml')
            ->run()->getExitCode()
        );
    }
}

exit(\Robo\Robo::run($_SERVER['argv'], RoboFile::class));